[package]
name = "my-jira"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.12"
ellipse = "0.2.0"
itertools = "0.13.0"
clearscreen = "3.0.0"
